#!/usr/bin/env bash
# Install a nginx web server listening on port 80.
# When making a GET request to nginx at its root /
#  it returns a page containing the string
# 'Hello World!'

apt-get update
apt-get install -y nginx

mkdir /etc/nginx/html
touch /etc/nginx/html/index.html
echo "Hello World!" > /etc/nginx/html/index.html
printf %s "server {
     listen      80 default_server;
     listen      [::]:80 default_server;
     root        /etc/nginx/html;
     index       index.html index.htm;
}
" > /etc/nginx/sites-available/default

service nginx restart
