#!/usr/bin/env bash
# Sets up an Nginx server to redirect /redirect_me to a different page.
# Configures a "301 Moved Permanently" redirection
# for /redirect_me on the Nginx server.

apt-get update
apt-get install -y nginx
echo "Hello World!" > /etc/nginx/html/index.html
echo "server {
    listen 80;
    listen [::]:80 default_server;
    root   /etc/nginx/html;
    index  index.html;
    location /redirect_me {
        return 301 https://get.tech/;
    }
}" > /etc/nginx/sites-available/default
service nginx restart
