#!/usr/bin/env bash
# Install a nginx web server listening on port 80.
# When sending a GET request to the root of the
# Nginx server (/) it returns a page containing
# the text 'Hello World!'.

# Sets up an Nginx server directive to redirect
# To another page with a 301 HTTP status code.
#
# Sets up a custom 404 page with the content
# 'Ceci n'est pas une page' on the Nginx server.

sudo apt-get update
sudo apt-get install -y nginx

# Creating an index.html page
echo "Hello World!" | sudo tee /var/www/html/index.html

# Performing a "moved permanently redirection" (301)
new_string="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/anthonyosigbe permanent;"
sudo sed -i "s/server_name _;/$new_string/" /etc/nginx/sites-enabled/default

# Creating a 404 Custom error page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
new_string="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"

sudo sed -i "s/listen 80 default_server;/$new_string/" /etc/nginx/sites-enabled/default

# Testing configurations for syntax errors
sudo nginx -t

sudo service nginx restart
