#!/usr/bin/env bash
# Sets up HAProxy with the subsequent configurations:
# Allows management of HAproxy via the init script.
# Balances requests using a round-robin algorithm.

# Install and configure HAproxy on my 425854-lb-01 server.
sudo apt-get -y update
apt-get -y install haproxy

# edit config file
server_config=\
"
frontend  thronehub_frontend
        bind *:80
        mode http
        default_backend thronehub_backend
backend thronehub_backend
        balance roundrobin
        server 425854-web-01 34.229.68.30:80 check
        server 425854-web-02 100.25.3.119:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

# Testing the HAproxy configuration file
sudo haproxy -c -f /etc/haproxy/haproxy.cfg

# Restart the Nginx service
sudo service haproxy restart
