#!/usr/bin/env bash
# Sets up HAProxy version 2.9 with the subsequent configurations:
# Allows management of HAproxy via the init script.
# Balances requests using a round-robin algorithm.

# Install HAproxy on a server
apt-get -y update
apt-get -y install haproxy=2.8.\*

# Configure haproxy configuration file to distribute requests using a roundrobin algorithm
echo '
frontend thronehub.tech
        bind 0:80
        default_backend web_servers

backend web_servers
        balance roundrobin
        server 425854-web-01 34.229.68.30:80
        server 425854-web-02 54.158.220.29:80
' >> /etc/haproxy/haproxy.cfg

# Restart HAproxy service
sudo service haproxy restart
