#!/usr/bin/env bash
# Tells a story based on the contents of the `/etc/passwd` file.

passwd_file="/etc/passwd"

while IFS=: read -r username password uid gid user_info home shell; do
    echo "The user $username is part of the $gid gang, lives in $home, and rides $shell."
    echo "USER ID's place is protected by the passcode $password, more info about the user here: $user_info"
    echo
done < "$passwd_file"
