#!/usr/bin/env bash
# Tells a story based on the contents of the /etc/passwd file.

while IFS=':' read -r username password uid gid info home shell; do
  if [[ "$username" == "#"* ]]; then
    # Skip comment lines
    continue
  fi
  echo "The user $username is part of the $gid gang,"
  echo "lives in $home and rides $shell."
  echo "$uid's place is protected by the passcode $password,"
  echo "more info about the user here: $info"
  echo  # Add a line break for readability
done < "/etc/passwd"

